In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("austo_automobile.csv")

In [3]:
df

,Age,Gender,Profession,Marital_status,Education,No_of_Dependents,Personal_loan,House_loan,Partner_working,Salary,Partner_salary,Total_salary
0,33,Male,Business,Married,Graduate,2.0,No,No,Yes,50392,75606.0,125998.0
1,32,Female,Salaried,Married,Graduate,3.0,Yes,No,No,30887,0.0,30887.0
2,59,Female,Business,Married,Graduate,4.0,No,Yes,Yes,35361,40195.0,75556.0
3,55,Male,Salaried,Married,Graduate,4.0,No,Yes,Yes,46473,83234.0,129707.0
4,40,Male,Business,Single,Graduate,1.0,Yes,Yes,Yes,83869,42516.0,126385.0
...,...,...,...,...,...,...,...,...,...,...,...,...
5295,30,Female,Business,Married,Graduate,2.0,No,No,Yes,107122,63074.0,170196.0
5296,26,Male,Salaried,Single,Graduate,1.0,Yes,No,No,52928,0.0,52928.0
5297,37,Femal,Business,Married,Graduate,1.0,No,No,Yes,116896,92480.0,209376.0
5298,39,Male,Business,Single,Graduate,4.0,No,No,No,50918,0.0,50918.0
5299,36,Male,Salaried,Single,Post Graduate,1.0,No,No,Yes,113074,42881.0,155955.0

In [4]:
df.head()

,Age,Gender,Profession,Marital_status,Education,No_of_Dependents,Personal_loan,House_loan,Partner_working,Salary,Partner_salary,Total_salary
0,33,Male,Business,Married,Graduate,2.0,No,No,Yes,50392,75606.0,125998.0
1,32,Female,Salaried,Married,Graduate,3.0,Yes,No,No,30887,0.0,30887.0
2,59,Female,Business,Married,Graduate,4.0,No,Yes,Yes,35361,40195.0,75556.0
3,55,Male,Salaried,Married,Graduate,4.0,No,Yes,Yes,46473,83234.0,129707.0
4,40,Male,Business,Single,Graduate,1.0,Yes,Yes,Yes,83869,42516.0,126385.0

In [5]:
df.tail()

,Age,Gender,Profession,Marital_status,Education,No_of_Dependents,Personal_loan,House_loan,Partner_working,Salary,Partner_salary,Total_salary
5295,30,Female,Business,Married,Graduate,2.0,No,No,Yes,107122,63074.0,170196.0
5296,26,Male,Salaried,Single,Graduate,1.0,Yes,No,No,52928,0.0,52928.0
5297,37,Femal,Business,Married,Graduate,1.0,No,No,Yes,116896,92480.0,209376.0
5298,39,Male,Business,Single,Graduate,4.0,No,No,No,50918,0.0,50918.0
5299,36,Male,Salaried,Single,Post Graduate,1.0,No,No,Yes,113074,42881.0,155955.0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5300 entries, 0 to 5299
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Age               5300 non-null   int64
 1   Gender            5092 non-null   object
 2   Profession        5092 non-null   object
 3   Marital_status    5300 non-null   object
 4   Education         5300 non-null   object
 5   No_of_Dependents  5092 non-null   float64
 6   Personal_loan     5300 non-null   object
 7   House_loan        5300 non-null   object
 8   Partner_working   5300 non-null   object
 9   Salary            5300 non-null   int64
 10  Partner_salary    5092 non-null   float64
 11  Total_salary      5092 non-null   float64
dtypes: float64(3), int64(2), object(7)
memory usage: 497.0+ KB

In [7]:
df.columns

Index(['Age', 'Gender', 'Profession', 'Marital_status', 'Education',
       'No_of_Dependents', 'Personal_loan', 'House_loan', 'Partner_working',
       'Salary', 'Partner_salary', 'Total_salary'],
      dtype='object')

In [8]:
df.dtypes

Age                   int64
Gender               object
Profession           object
Marital_status       object
Education            object
No_of_Dependents    float64
Personal_loan        object
House_loan           object
Partner_working      object
Salary                int64
Partner_salary      float64
Total_salary        float64
dtype: object

In [9]:
df.isnull().sum()

Age                   0
Gender              208
Profession          208
Marital_status        0
Education             0
No_of_Dependents    208
Personal_loan         0
House_loan            0
Partner_working       0
Salary                0
Partner_salary      208
Total_salary        208
dtype: int64

In [10]:
df.shape

(5300, 12)

In [11]:
df.select_dtypes(include = ['int64' , 'float64'])

      Age  No_of_Dependents  Salary  Partner_salary  Total_salary
0      33               2.0   50392         75606.0      125998.0
1      32               3.0   30887             0.0       30887.0
2      59               4.0   35361         40195.0       75556.0
3      55               4.0   46473         83234.0      129707.0
4      40               1.0   83869         42516.0      126385.0
...   ...               ...     ...             ...           ...
5295   30               2.0  107122         63074.0      170196.0
5296   26               1.0   52928             0.0       52928.0
5297   37               1.0  116896         92480.0      209376.0
5298   39               4.0   50918             0.0       50918.0
5299   36               1.0  113074         42881.0      155955.0

[5300 rows x 5 columns]

In [12]:
df.select_dtypes(include = ['object'])

,Gender,Profession,Marital_status,Education,Personal_loan,House_loan,Partner_working
0,Male,Business,Married,Graduate,No,No,Yes
1,Female,Salaried,Married,Graduate,Yes,No,No
2,Female,Business,Married,Graduate,No,Yes,Yes
3,Male,Salaried,Married,Graduate,No,Yes,Yes
4,Male,Business,Single,Graduate,Yes,Yes,Yes
...,...,...,...,...,...,...,...
5295,Female,Business,Married,Graduate,No,No,Yes
5296,Male,Salaried,Single,Graduate,Yes,No,No
5297,Femal,Business,Married,Graduate,No,No,Yes
5298,Male,Business,Single,Graduate,No,No,No
5299,Male,Salaried,Single,Post Graduate,No,No,Yes

In [13]:
df.describe()

,Age,No_of_Dependents,Salary,Partner_salary,Total_salary
count,5300.000000,5092.000000,5300.000000,5092.000000,5092.000000
mean,40.713774,2.032600,74821.893962,36629.279851,111399.937156
std,10.924459,1.412448,26120.763607,33334.703135,42202.231497
min,22.000000,0.000000,30005.000000,0.000000,30006.000000
25%,31.000000,1.000000,52239.500000,0.000000,80827.500000
50%,41.000000,2.000000,75267.000000,37709.000000,110686.000000
75%,50.000000,3.000000,97346.000000,66324.000000,142776.000000
max,59.000000,4.000000,119994.000000,94976.000000,212065.000000

In [14]:
df.Gender.unique()

array(['Male', 'Female', 'Femal', nan], dtype=object)

In [15]:
df.Profession.unique()

array(['Business', 'Salaried', nan], dtype=object)

In [16]:
df.Marital_status.unique()

array(['Married', 'Single'], dtype=object)

In [17]:
df.Education.unique()

array(['Graduate', 'Post Graduate'], dtype=object)

In [1]:
import os
os.getcwd()

'C:\\Users\\Lenovo\\INTERNSHIP'